// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcL4NQ_typV6Q6pht2dg1o0qYZ8ezM2SU',
    appId: '1:833102393471:web:72916244f3762e58c3cf4a',
    messagingSenderId: '833102393471',
    projectId: 'patient-management-b833e',
    authDomain: 'patient-management-b833e.firebaseapp.com',
    databaseURL:
        'https://patient-management-b833e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patient-management-b833e.appspot.com',
    measurementId: 'G-RQ5GHNB4RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNsft30MXl0137qsebzskMWFXu9ZWwRQw',
    appId: '1:833102393471:android:5aba9eee32bc99bec3cf4a',
    messagingSenderId: '833102393471',
    projectId: 'patient-management-b833e',
    databaseURL:
        'https://patient-management-b833e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patient-management-b833e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvhmWqN20EB0o_a0EVazJ4jiGA2wsGtY',
    appId: '1:833102393471:ios:0f1e6f0cc40f6d8bc3cf4a',
    messagingSenderId: '833102393471',
    projectId: 'patient-management-b833e',
    databaseURL:
        'https://patient-management-b833e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patient-management-b833e.appspot.com',
    iosClientId:
        '833102393471-pkd5gq5evmphspi0rhlbmdcbmg0n9t4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabeticheroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvhmWqN20EB0o_a0EVazJ4jiGA2wsGtY',
    appId: '1:833102393471:ios:0f1e6f0cc40f6d8bc3cf4a',
    messagingSenderId: '833102393471',
    projectId: 'patient-management-b833e',
    databaseURL:
        'https://patient-management-b833e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'patient-management-b833e.appspot.com',
    iosClientId:
        '833102393471-pkd5gq5evmphspi0rhlbmdcbmg0n9t4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabeticheroApp',
  );
}
